### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by Shifty-1337** [rcmaehl/NotCPUCores#8]
Hey!
I am wondering why does your program consumes so 15% of my cpu.
My computer is:
XEON 1230 v3 
Gtx 1070
16GB ram (4x4 GB CL9 1600Mhz )
https://i.imgur.com/r1XSP7k.png

**Comment by rcmaehl** [comment]
Hi Shifty-1337,

Looks like the program does have this issue when optimizing some processes. I'm working on a patch and it should be out within a couple hours. 

Regards,

Robert M.

**Comment by rcmaehl** [comment]
Hi Shifty-1337,

Please try out [Release 1.3.1.0](https://github.com/rcmaehl/NotCPUCores/releases/tag/1.3.1.0) and see if it resolves your issue

**Comment by Shifty-1337** [comment]
Seems fixed now:
https://i.imgur.com/kkLW3B4.png
Also could you remove the feature that it automatically selects the balanced power plan? I mean i like to keep it mine on performance but this keeps changing it back to balanced.

Also Add some kind of tick box that "advanced user" and allow real time setting not only "high".
If it is only assigned to 4-5 cores out of the 8 then setting it to realtime makes sense because the remaning cores can take care of other stuff and the system does not lock up. (Do no allow this to 4 cores though because it would just lock the system up but with 4+ cores realtime setting is viable.

**Comment by rcmaehl** [comment]
>Also could you remove the feature that it automatically selects the balanced power plan?

Oops, that's actually a bug. Will fix

>allow real time setting not only "high"

Yeah, I can add an advanced feature for this

**Comment by rcmaehl** [comment]
Hi Shifty-1337,

The power plan issue should now be resolved and there is now a checkbox for using RealTime priority over High priority in release [1.4.0.0](https://github.com/rcmaehl/NotCPUCores/releases/tag/1.4.0.0).

**Comment by rcmaehl** [comment]
Hi Shifty-1337,

This should send you another email notification in regards to this issue. I follow my work's standard of 3 contact attempts before ticket closure. If 1.4.0.0 did not fix your additional requests let me know.

Thanks!
Robert M

**Comment by rcmaehl** [comment]
Hi Shifty-1337,

This should send you another email notification in regards to this issue. I follow my work's standard of 3 contact attempts before ticket closure. If 1.4.0.0 did not fix your additional requests let me know, if not I will be closing this issue next time I access github.

Thanks!
Robert M
